services:
    bdtln_user.change_password.form.type:
        class: Bdtln\UserBundle\Form\Type\ChangePasswordFormType
        tags:
            - { name: form.type, alias: bdtln_user_change_password }
#    bdtln_user.example:
#        class: Bdtln\UserBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
