<?php

namespace Bdtln\AxeBundle\Entity;

/**
 * AxeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AxeRepository extends \Doctrine\ORM\EntityRepository
{
    
    /**
     * findAllWithProject() will find all axes and do a join to get the projects in only once query
     * @return ArrayCollection the list of all axes linked with their all projects
     */
    public function findAllWithProjects() {
        //Creating of querybuilder
        $queryBuilder = $this->_em->createQueryBuilder('a');
        //Select all from axe with a join between axe and project 
        $queryBuilder->select('a')
                    ->from('BdtlnAxeBundle:Axe', 'a')
                    ->leftJoin('a.projects', 'p')
                    ->addSelect('p');
        
        return $queryBuilder->getQuery()->getResult();
    }
    
    
}
