<?php

namespace Bdtln\ProjectBundle\Entity;

/**
 * AttachedFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttachedFileRepository extends \Doctrine\ORM\EntityRepository
{
}
