<?php

namespace Bdtln\UserBundle\Entity;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    
    /**
     * setCagegoryNull set field category to null for a given id
     * @param integer $idCategory
     */
    public function setCategoryNull( $idCategory ) {
        
        $queryBuilder = $this->_em->createQueryBuilder('u');
        
        $q = $queryBuilder->update('BdtlnUserBundle:User', 'u')
                     ->set('u.category', "NULL")
                     ->where('u.category = :idcategory')
                     ->setParameter('idcategory', $idCategory)
                     ->getQuery();
            ;
        $q->execute();
        
    }
    

    
}
